version: '3.5'

services:
  psql:
    image: postgres:15.4
    container_name: postgres-sample
    ports:
      - "32770:5432"
    environment:
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_USER=postgres
    command: [ "postgres", "-c", "wal_level=logical" ]
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
