spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "https://localhost:4200"
            allowedMethods: "*"
            allowedHeaders: "*"

server:
  port: 8100
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    preferIpAddress: true
    instanceId: 
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
