version: "3.9"
networks:
  park20:
    name: park20
    driver: bridge

services:

  #RabbitMQ
  rabbitmq:
    container_name: rabbitmq4
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      park20:
        aliases:
          - rabbitmq4


  #Park BackOffice 1
  db_park_bo_mcs_1:
    container_name: db_park_bo_mcs_1
    hostname: db_park_bo_mcs_1
    build: ./db_park_bo_mcs
    environment:
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_USER=postgres
    ports:
      - "5502:5432"
    command: [ "postgres", "-c", "wal_level=logical" ]
    networks:
      park20:
        aliases:
          - db_park_bo_mcs_1

  #Payment BackOffice 1
  db_payments_bo_mcs_1:
    container_name: db_payments_bo_mcs_1
    hostname: db_payments_bo_mcs_1
    build: ./db_payments_bo_mcs
    environment:
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_USER=postgres
    ports:
      - "5506:5432"
    command: [ "postgres", "-c", "wal_level=logical" ]
    networks:
      park20:
        aliases:
          - db_payments_bo_mcs_1

  #User BackOffice 1
  db_users_bo_mcs_1:
    container_name: db_users_bo_mcs_1
    hostname: db_users_bo_mcs_1
    build: ./db_users_bo_mcs
    environment:
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_USER=postgres
    ports:
      - "5510:5432"
    command: [ "postgres", "-c", "wal_level=logical" ]
    networks:
      park20:
        aliases:
          - db_users_bo_mcs_1